### PR TITLE
Typo in function name

### PR DESCRIPTION
**Pull request by starkskalle**
Fixing a typo as discussed on Slack

### CODE REVIEW

**Comment by michalbundyra** [comment]
Thanks, @starkskalle!

**Comment by boesing** [comment]
@michalbundyra this is already merged, isnt it?

**Comment by michalbundyra** [comment]
@boesing not sure what has happened, it was merged just to develop, now merged to master as well. thanks

**Comment by michalbundyra** [comment]
Thanks, @starkskalle!

**Pull request merged**
